services:
  ga_nav:
    extends:
      file: docker-compose-gui.yaml
      service: ga_nav
    environment:
     - NVIDIA_VISIBLE_DEVICES=all
     - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia
